/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
const bcrypt = require("bcrypt");
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("users").del();
  await knex("users").insert([
    {
      username: "user1",
      first_name: "John",
      last_name: "Doe",
      email: "user1@example.com",
      password: await bcrypt.hash("password1", await bcrypt.genSalt(10)),
      date_of_birth: "1990-01-01",
      state: "California",
      city: "Los Angeles",
      phone_number: "123-456-7890",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    // User 2
    {
      username: "user2",
      first_name: "Jane",
      last_name: "Smith",
      email: "user2@example.com",
      password: await bcrypt.hash("password2", await bcrypt.genSalt(10)),
      date_of_birth: "1985-05-15",
      state: "New York",
      city: "New York City",
      phone_number: "987-654-3210",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    // Add more users as needed, each with hashed passwords
    // User 3
    {
      username: "user3",
      first_name: "Alice",
      last_name: "Johnson",
      email: "user3@example.com",
      password: await bcrypt.hash("password3", await bcrypt.genSalt(10)),
      date_of_birth: "1988-12-10",
      state: "Texas",
      city: "Austin",
      phone_number: "555-123-4567",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    // User 4
    {
      username: "user4",
      first_name: "Michael",
      last_name: "Williams",
      email: "user4@example.com",
      password: await bcrypt.hash("password4", await bcrypt.genSalt(10)),
      date_of_birth: "1992-07-20",
      state: "Florida",
      city: "Miami",
      phone_number: "555-987-6543",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },

    {
      username: "user5",
      first_name: "Emma",
      last_name: "Brown",
      email: "user5@example.com",
      password: await bcrypt.hash("password5", await bcrypt.genSalt(10)),
      date_of_birth: "1995-03-25",
      state: "California",
      city: "San Francisco",
      phone_number: "555-111-2222",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      username: "user6",
      first_name: "Michael",
      last_name: "Lee",
      email: "michael.lee@example.com",
      password: await bcrypt.hash("password6", await bcrypt.genSalt(10)),

      date_of_birth: "1975-07-12",
      state: "Ohio",
      city: "Columbus",
      phone_number: "1112223333",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      username: "user7",
      first_name: "Sarah",
      last_name: "Garcia",
      email: "sarah.garcia@example.com",
      password: await bcrypt.hash("password7", await bcrypt.genSalt(10)),
      date_of_birth: "1985-12-30",
      state: "Arizona",
      city: "Phoenix",
      phone_number: "7776665555",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      username: "user8",
      first_name: "David",
      last_name: "Martinez",
      email: "david.martinez@example.com",
      password: await bcrypt.hash("password8", await bcrypt.genSalt(10)),
      date_of_birth: "1993-09-08",
      state: "Colorado",
      city: "Denver",
      phone_number: "2223334444",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      username: "user9",
      first_name: "Jessica",
      last_name: "Lopez",
      email: "jessica.lopez@example.com",
      password: await bcrypt.hash("password9", await bcrypt.genSalt(10)),
      date_of_birth: "1983-04-18",
      state: "Washington",
      city: "Seattle",
      phone_number: "4445556666",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      username: "user10",
      first_name: "Matthew",
      last_name: "Hernandez",
      email: "matthew.hernandez@example.com",
      password: await bcrypt.hash("password10", await bcrypt.genSalt(10)),
      date_of_birth: "1990-06-05",
      state: "Georgia",
      city: "Atlanta",
      phone_number: "6667778888",
      role: "user",
      third_party_login: false,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);
};
